version: 2
sources:
   - name: gz_raw_data
     description: "Data set de base"
     tables:
         - name: raw_gz_product
           description: "ma table primaire de productions"
           columns:
            - name: products_id
              tests:
                - unique
                - not_null
         - name: raw_gz_sales
           description: "ma table primaire de ventes"
           columns:
            - name: pdt_id
           tests:
            - unique:
              column_date: "(orders_id || '-' || pdt_id)"
            - not_null:
              column_date: "(orders_id || '-' || pdt_id)"
         - name: raw_gz_ship
           description: "ma table primaire d'envoi"
           columns:
            - name: orders_id
              tests:
                - unique
                - not_null







